# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71fed59fd6f50e996d25278996df82abf1fe4468e12a4755717a7c3825c26a69c4a6c353f8dfe963ae75e11d5d34758f0437c72f11da6fdf32de4800a31727bc

test:
  secret_key_base: 0a2db4a24300c61baaac97aa473b5333a7e0efb4425c56d6b08cabe93962baed184fb18d2107e781c3d79eeb038428ec607e9a4250b47a3227877faefd273875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
